
/******************************************************************************
 * @file      startup_stm32f401cdux.s
 * @author    Auto-generated by STM32CubeIDE
 *
 * BLACK PILL LED BLINKING IN ASSEMBLER 34 BYTES LONG !!
 ******************************************************************************/

.syntax unified
.cpu cortex-m4
.fpu softvfp
.thumb

//==========================================================
#define RCC_AHB1_ADDR             0x40023800
#define RCC_AHB1_EN_OFFSET        0x30
#define ENABLE_GPIOC_VALUE        0x04
#define GPIOC_ODR_REG_OFFSET      0x14
//============================================================================================
/* 1. RCC->AHB1_ENR = 0x04 ; ENABLE RCC CLOCK FOR GPIOC (0x40023830 ADDRESS)  */
/* 2. GPIOC->MODER = 0x04000000 (1 << 26) SET GPIOC BIT 13 TO OUTPUT PUSH_PULL at  (0x40020800  ADDRESS) */
/* 3. GPIOC->ODR TOGGLE BIT 13 IN GPIOC->ODR REGISTER (0x40020814  ADDRESS)  */
/* 4. A SMALL DELAY LOOP */
/* 5. GO BACK TO TOGGLE BIT 13 IN GPIOC->ODR REGISTER */
//============================================================================================

//*******************************
  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
//*******************************
//---
  .word RCC_AHB1_ADDR       // SP = 0x40023800 STACK POINTER VALUE IT REALLY DOESN'T MATTER - STACK IS UNUSED
  .word Reset_Handler       // THE Reset_Handler POINTER
//---
Reset_Handler:
/* 1. RCC->AHB1_ENR = 0x04 ; ENABLE RCC CLOCK FOR GPIOC (0x40023830 ADDRESS)  */
//---
    // SP = 0x40023800 BASE RCC
    MOVS    R2, #ENABLE_GPIOC_VALUE              // R2 = 0x04 = BASE TO OTHER 1 BIT VALUES
    STR     R2, [SP, RCC_AHB1_EN_OFFSET]         // RCC->AHB1_ENR = 0x04 ; ENABLE GPIOC CLOCK 0x30 = RCC_AHB1_EN_OFFSET
//---
/* 2. GPIOC->MODER = 0x04000000 (1 << 26) SET GPIOC BIT 13 TO OUTPUT PUSH_PULL at  (0x40020800  ADDRESS) */
    SUBS    R0, SP, 0x3000                       // R0 = 0x40020800 = GPIOC BASE R0 = SP - 0x3000 = (0x40023800 - 0x3000) = 0x40020800
//---
    LSLS    R1, R2, #24                          // R1 = 0x04 << 24 = BIT_13_REGVALUE_SETUP
    STR     R1, [R0]                             // INITIAL VALUE GPIOC_MODER_REGISTER = BIT13 SET TO OUTPUT
//---
    LSLS    R3, R2, #11                          // R3 = 0x2000 = (1 << 13)
//---
LOOP01:
/* 3. GPIOC->ODR TOGGLE BIT 13 IN GPIOC->ODR REGISTER (0x40020814  ADDRESS)  */
    EORS    R2, R3                               // TOGGLE BIT 13
    STR     R2, [R0, #GPIOC_ODR_REG_OFFSET]      // STORE VALUE WITH TOGGLED BIT 13 INTO GPIOC_ODR_REGISTER
//---
    LSLS    R1, R3, #6                           // R1 = 0x2000 << 6 = 0x00080000 = 524288 => R1 = delay counter
//---
LOOP02:
/* 4. A SMALL DELAY LOOP */
    SUBS   R1,#1                                 // DECREMENT REGISTER
    BNE    LOOP02                                // REGISTER NOT 0? SO STILL DECREMENT
//---
/* 5. GO BACK TO THE TOGGLE BIT 13 IN GPIOC->ODR REGISTER */
    BEQ    LOOP01                                // NEVERENDING LOOP
/*****END OF FILE****/

